name: Build Boardwalk

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download libraries
      run: tools/download_libraries.sh

    - name: Build with Gradle
      run: ./gradlew build
